on:
  push: {branches: master}
  pull_request: {branches: master}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1.0.2
        with: {go-version: '1.12.7'}
      - uses: actions/checkout@v1.0.0
      - run: go test ./...
