on: repository_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1.0.2
        with: {go-version: '1.12.7'}
      - uses: actions/checkout@v1.0.0
      - run: go test ./...
      - run: script/build ${{github.event.action}}
      - uses: jclem/github-release@master
        with:
          tag-name: ${{github.event.action}}
          name: ${{github.event.action}}
          draft: true
          assets: 'build/*.tar.gz'
          github-token: ${{github.token}}
